import { getCurrentSpan, tool, type Tool, type ToolCallOutputContent, type RunContext } from "@openai/agents";
import type { McpToolResult } from "@/domain/llm/types";
import { imageDataUrl } from "@/domain/llm/types";
import { describeImageInputReject } from "@/domain/llm/models";
import { MAX_IMAGES_PER_TURN } from "@/domain/llm/imageLimits";
import { AUDIO_TOOL_NAMES, FILE_TOOL_NAME } from "@/domain/llm/toolNames";
import {
  SKILL_TOOL_NAME, IMAGE_TOOL_NAME, EDIT_IMAGE_TOOL_NAME, FETCH_URL_TOOL_NAME,
  SAVE_FILE_TOOL_NAME, SLACK_TOOL_NAMES,
  type AgentRunAssembly,
} from "@/application/llm/agentAssembly";
import type { PiiFilter } from "@/application/llm/pii";
import { framedFetchedUrl } from "@/application/llm/documentParts";
import type { AgentDeps, RunAgentInput } from "./types";
import type { RuntimeTurn } from "./model";
import { restoreValues } from "./messages";
import { boundToolArgsPair } from "./arguments";
import type { RuntimeEmitter } from "./output";
import { createSdkMcp, type McpCapability, type ToolCallDetails } from "./mcp";

type CapabilityOutput = McpToolResult & { bounded?: boolean };

const MAX_URL_FETCHES_PER_RUN = 20;
const MAX_SAVED_FILES_PER_RUN = 10;

/** The SDK invokes these capabilities; this module never advances agent turns. */
export function createRuntimeTools(
  deps: AgentDeps, input: RunAgentInput, assembly: AgentRunAssembly,
  turn: RuntimeTurn, emit: RuntimeEmitter, filter?: PiiFilter,
) {
  const resources = turn.resources ??= { urls: 0, files: 0, imageTurn: 0, imagesUsed: 0 };
  let lossReported = false;
  let serial = Promise.resolve();
  const imageInputReject = describeImageInputReject(input.model);
  const serverByTool = new Map((input.mcpServers ?? []).flatMap((server) => server.toolNames.map((name) => [name, server.name] as const)));

  async function invoke(name: string, args: Record<string, unknown>, display: Record<string, unknown>): Promise<CapabilityOutput> {
    const builtin = assembly.builtinNames.has(name);
    if (!builtin) return deps.callMcpTool ? deps.callMcpTool(name, display) : { text: `Error: Tool '${name}' cannot be executed in this context.` };
    if (name === SKILL_TOOL_NAME) {
      const skill = string(display.skill_name);
      if (!(input.skills ?? []).some((entry) => entry.name === skill)) return { text: `Error: skill '${skill}' is not available. Available skills: ${(input.skills ?? []).map((entry) => entry.name).join(", ")}.`, bounded: true };
      return { text: await deps.loadSkillContent!(skill, typeof display.file_path === "string" ? display.file_path : undefined) };
    }
    if (name === IMAGE_TOOL_NAME || name === EDIT_IMAGE_TOOL_NAME) {
      if (!string(args.prompt).trim()) return { text: `Error: ${name} requires a prompt.`, bounded: true };
      const options = { size: typeof display.size === "string" ? display.size : undefined, quality: typeof display.quality === "string" ? display.quality : undefined };
      const source = assembly.images.get(string(display.image_id));
      if (name === EDIT_IMAGE_TOOL_NAME && !source) return { text: `Error: no image with id '${string(display.image_id)}'. Available images: ${assembly.images.list().map((image) => image.id).join(", ")}.`, bounded: true };
      const image = name === IMAGE_TOOL_NAME
        ? await deps.generateImage!(string(args.prompt), options.size, options.quality)
        : await deps.editImage!({ prompt: string(args.prompt), images: [source!], ...options });
      const handle = assembly.images.add(image, `generated by ${name}`);
      emit({ image: { ...image, prompt: string(display.prompt) } });
      return { text: `Image generated and delivered to the user (image id: ${handle.id}). Briefly describe the result.` };
    }
    if (name === FETCH_URL_TOOL_NAME) {
      const url = string(display.url).trim();
      if (!url) return { text: "Error: FetchUrl requires a url.", bounded: true };
      if (resources.urls >= MAX_URL_FETCHES_PER_RUN) return { text: `Error: this run has already read ${MAX_URL_FETCHES_PER_RUN} addresses, which is its limit.`, bounded: true };
      resources.urls += 1;
      const result = await deps.fetchUrl!(url);
      return { text: result.image ? `Image fetched from ${url}.` : framedFetchedUrl(url, result.text, result.note), ...(result.image ? { images: [result.image] } : {}) };
    }
    if (name === SAVE_FILE_TOOL_NAME || name === FILE_TOOL_NAME) {
      const writes = name === SAVE_FILE_TOOL_NAME || display.operation === "create" || display.operation === "edit";
      if (writes && resources.files >= MAX_SAVED_FILES_PER_RUN) return { text: `Error: this run has already written ${MAX_SAVED_FILES_PER_RUN} files, which is its limit.`, bounded: true };
      if (writes) resources.files += 1;
      return name === SAVE_FILE_TOOL_NAME
        ? deps.saveFile!({ name: string(display.name), mimeType: string(display.mime_type), content: string(display.content) })
        : deps.fileTool!(display);
    }
    if (AUDIO_TOOL_NAMES.includes(name)) return deps.audioTools!(name, display);
    if (SLACK_TOOL_NAMES.includes(name)) return { text: await deps.readSlack!(name, display) };
    return { text: `Error: Tool '${name}' cannot be executed in this context.`, bounded: true };
  }

  const mcp: McpCapability[] = [];
  const tools: Tool[] = [];
  for (const definition of assembly.tools.filter((definition) => !assembly.delegations.some((binding) => binding.name === definition.function.name) && !input.parameters?.policy?.blockedTools?.includes(definition.function.name))) {
    const name = definition.function.name;
    const displayNames = new Map<string, string>();
    const showResult = (id: string, raw: string, boundedText = false) => {
      const masked = filter?.mask(raw) ?? raw;
      const bounded = (boundedText ? turn.results.charge : turn.results.fit)(masked);
      if (bounded.startsWith("Error:")) getCurrentSpan()?.setError({ message: "Tool execution failed" });
      emit({ toolResult: { toolCallId: id, name: displayNames.get(id) ?? (serverByTool.has(name) ? `${serverByTool.get(name)}: ${name}` : name), content: filter?.restore(bounded) ?? bounded } });
      if (bounded !== masked && !lossReported) {
        lossReported = true;
        emit({ warning: "Tool output was truncated to fit the run's context budget." });
      }
      return bounded;
    };
    const options = {
      name, description: definition.function.description ?? name,
      strict: false as const,
      parameters: { properties: {}, required: [], ...definition.function.parameters, type: "object" as const, additionalProperties: true as const },
      needsApproval: assembly.clientToolNames.has(name) || input.parameters?.policy?.approvalTools?.includes(name),
      errorFunction: async (_context: RunContext<unknown>, error: unknown, details?: ToolCallDetails) => {
        const id = details?.toolCall?.callId ?? "";
        const slot = turn.toolOrder?.get(id);
        if (slot) await waitForSlot(slot.previous, details?.signal ?? input.signal);
        try { return showResult(id, `Error: ${error instanceof Error ? error.message : String(error)}`); }
        finally { slot?.complete(); }
      },
      execute: async (raw: unknown, _context: RunContext<unknown> | undefined, details?: ToolCallDetails): Promise<string | ToolCallOutputContent[]> => {
        input.signal?.throwIfAborted();
        const callId = details?.toolCall?.callId ?? "";
        const slot = claimToolSlot(turn, callId);
        if (!raw || typeof raw !== "object" || Array.isArray(raw)) {
          await waitForSlot(slot.previous, details?.signal ?? input.signal);
          try { return showResult(callId, "Error: tool arguments must be a JSON object."); }
          finally { slot.complete(); }
        }
        const args = raw as Record<string, unknown>;
        const display = filter ? restoreValues(filter, args) as Record<string, unknown> : args;
        if (name === SKILL_TOOL_NAME && string(display.skill_name)) displayNames.set(callId, `${name}: ${string(display.skill_name)}`);
        if (details?.toolCall) details.toolCall.arguments = JSON.stringify(boundToolArgsPair(args, display).wire);
        const action = () => invoke(name, args, display);
        const sequential = [IMAGE_TOOL_NAME, EDIT_IMAGE_TOOL_NAME, SKILL_TOOL_NAME, ...SLACK_TOOL_NAMES].includes(name);
        const task = sequential ? serial.then(action) : action();
        if (sequential) serial = task.then(() => {}, () => {});
        const result = await task;
        input.signal?.throwIfAborted();
        await waitForSlot(slot.previous, details?.signal ?? input.signal);
        try {
        for (const file of result.files ?? []) emit({ file: { ...file, source: `${assembly.builtinNames.has(name) ? "builtin" : "mcp"}: ${name}` } });
        if (resources.imageTurn !== turn.number) { resources.imageTurn = turn.number; resources.imagesUsed = 0; }
        const images = (result.images ?? []).slice(0, MAX_IMAGES_PER_TURN - resources.imagesUsed);
        resources.imagesUsed += images.length;
        const ids = [];
        for (const image of images) {
          ids.push(assembly.images.add(image, `returned by ${name}`).id);
          emit({ image: { ...image, prompt: `Returned by ${name}`, ...(name === FETCH_URL_TOOL_NAME ? { fetched: true } : {}) } });
        }
        let text = result.text;
        if (images.length) text += `\n${images.length} image(s) delivered to the user (image ids: ${ids.join(", ")})${imageInputReject ? `, but not to you: ${imageInputReject}` : ", and attached to the next message."}`;
        const dropped = (result.images?.length ?? 0) - images.length;
        if (dropped > 0) text += `\n${dropped} more were dropped: at most ${MAX_IMAGES_PER_TURN} images per turn.`;
        const content = showResult(callId, text, result.bounded);
        return images.length && !imageInputReject
          ? [{ type: "text", text: content }, ...images.map((image) => ({ type: "image" as const, image: imageDataUrl(image) }))]
          : content;
        } finally { slot?.complete(); displayNames.delete(callId); }
      },
    };
    if (!assembly.builtinNames.has(name) && !assembly.clientToolNames.has(name)) {
      mcp.push({ definition, server: serverByTool.get(name) ?? "MCP", needsApproval: Boolean(options.needsApproval), execute: options.execute, error: options.errorFunction });
    } else {
      const native = tool(options);
      native.name = name;
      tools.push(native);
    }
  }
  return { tools, mcp: createSdkMcp(mcp) };
}

function string(value: unknown): string { return typeof value === "string" ? value : ""; }

/** Only invoked tools spend result budget. SDK rejections and approvals hold no slot. */
export function claimToolSlot(turn: RuntimeTurn, id: string) {
  const order = turn.toolOrder ??= new Map();
  const existing = order.get(id);
  if (existing) return existing;
  const previous = [...order.values()].at(-1)?.finished ?? Promise.resolve();
  let complete!: () => void;
  const finished = new Promise<void>((resolve) => { complete = resolve; });
  const slot = { previous, finished, complete };
  order.set(id, slot);
  return slot;
}

export function waitForSlot(previous: Promise<void>, signal?: AbortSignal): Promise<void> {
  signal?.throwIfAborted();
  return new Promise((resolve, reject) => {
    const abort = () => reject(signal?.reason);
    signal?.addEventListener("abort", abort, { once: true });
    void previous.then(() => { signal?.removeEventListener("abort", abort); resolve(); });
  });
}
