/** Document parser and renderer work budgets. Transport limits belong to the caller. */

/** Office text output budget, owned by the document port; truncation retains unit counts. */
export { MAX_DOCUMENT_TOOL_CHARS as MAX_TEXT_CHARS } from "@/domain/document/processor";

/** Bound Markdown AST construction and rendering independently of transport bytes. */
export const MAX_MARKDOWN_CHARS = 500_000;

/**
 * What a compressed document may expand to, and how many parts it may have.
 *
 * DOCX and HWPX are zips and an HWP section is raw deflate, which means a small
 * upload can ask for an unbounded allocation — the compression ratio is the
 * archive author's to choose. The zip path checks what the central directory
 * *declares* before inflating anything, so a bomb costs a header read rather
 * than the memory it wanted; the HWP path has no such declaration and caps the
 * inflater's output instead.
 */
export const MAX_ZIP_ENTRIES = 2_000;
export const MAX_EXPANDED_BYTES = 100 * 1024 * 1024;
export const MAX_ZIP_ENTRY_BYTES = 25 * 1024 * 1024;
export const MAX_COMPRESSION_RATIO = 1_000;

/** Parser work budgets below the archive byte ceiling. */
export const MAX_XML_EVENTS = 1_000_000;
export const MAX_XML_DEPTH = 256;
export const MAX_SPREADSHEET_ROWS = 100_000;
export const MAX_SPREADSHEET_CELLS = 1_000_000;
export const MAX_INSPECTED_CELLS = 10_000;

/** Excel worksheet coordinates, independent of how many populated cells are parsed. */
export const MAX_SPREADSHEET_COLUMNS = 16_384;
export const MAX_SPREADSHEET_ROW_INDEX = 1_048_576;

/** ODF merged-cell geometry bound; repeated content uses the spreadsheet budgets above. */
export const MAX_ODF_CELL_SPAN = 256;

/** Bound each structure window and each block preview inside MAX_TEXT_CHARS. */
export const MAX_INSPECTED_BLOCKS = 500;
export const MAX_BLOCK_PREVIEW_CHARS = 120;

/** Document-port asset count and byte budgets shared by renderers. */
export { MAX_DOCUMENT_ASSETS as MAX_ASSET_COUNT } from "@/domain/document/processor";
export { MAX_DOCUMENT_ASSET_BYTES as MAX_ASSET_TOTAL_BYTES } from "@/domain/document/processor";

/** Bound generated bytes before worker transport or Artifact storage. */
export const MAX_RENDERED_BYTES = 10_000_000;
