#!/usr/bin/env bash
#
# Write `.env.secrets` and `.env.mcp.secrets` from SSM.
#
# The same parameters External Secrets pulls into the cluster, so the two
# instances hold the same values — which for AES_ENCRYPTION_KEY is not a
# convenience but the requirement: it decrypts the stored credentials in the
# table both read.
#
# Run it from a laptop with the SSO profile
# (`AWS_PROFILE=opspresso deploy/idc/scripts/fetch-env.sh`, then scp the two
# files over). The host's own IAM user cannot read SSM: no policy grants it, on
# purpose — a leaked access key would otherwise open every deployment secret.
# Granting it is a decision, not an oversight; make it in
# terraform-env-demo/demo/9-agentdure if the host should refresh its own.
#
# Generated whole every time. Nothing edits these files by hand, so there is no
# merge to get wrong.

set -euo pipefail

cd "$(dirname "$0")/.."

: "${AWS_REGION:=ap-northeast-2}"
export AWS_REGION

# A parameter's value, with the trailing newline the shell would otherwise carry
# into the file. A header cannot hold one, and the app reports such a value as
# unset rather than wrong.
param() {
  aws ssm get-parameter --name "$1" --with-decryption \
    --query 'Parameter.Value' --output text | tr -d '\n'
}

emit() {
  printf '%s=%s\n' "$1" "$(param "$2")"
}

write_secrets() {
  echo "# Generated by scripts/fetch-env.sh — do not edit."
  emit AES_ENCRYPTION_KEY              /k8s/common/agentdure/aes-encryption-key
  emit BETTER_AUTH_SECRET              /k8s/common/agentdure/better-auth-secret
  emit GOOGLE_CLIENT_ID                /k8s/common/agentdure/google-client-id
  emit GOOGLE_CLIENT_SECRET            /k8s/common/agentdure/google-client-secret
  emit LLM_API_KEY                     /k8s/common/agentdure/llm-api-key
  emit LLM_PROVIDER_OPENAI_API_KEY     /k8s/common/agentdure/llm-provider-openai-api-key
  emit LLM_PROVIDER_ANTHROPIC_API_KEY  /k8s/common/agentdure/llm-provider-anthropic-api-key
  emit LLM_PROVIDER_XAI_API_KEY        /k8s/common/agentdure/llm-provider-xai-api-key
  emit LLM_PROVIDER_OPENROUTER_API_KEY /k8s/common/agentdure/llm-provider-openrouter-api-key
  emit A2A_API_KEY                     /k8s/common/agentdure/a2a-api-key
  emit GITHUB_TOKEN                    /k8s/common/agentdure/github-token
  # Read by the app and by the ticker. With the ticker profile off the app just
  # answers 503 on the three scan endpoints, which is correct while the cluster
  # is the one ticking.
  emit SCHEDULE_SCAN_TOKEN             /k8s/common/agentdure/schedule-scan-token
}

write_mcp_secrets() {
  echo "# Generated by scripts/fetch-env.sh — do not edit."
  emit BRAVE_API_KEY    /k8s/common/mcp-brave-search/brave-api-key
  emit ARGOCD_API_TOKEN /k8s/common/mcp-argocd/argocd-api-token
}

umask 077
write_secrets > .env.secrets
write_mcp_secrets > .env.mcp.secrets

echo "wrote .env.secrets ($(grep -c '=' .env.secrets) values) and .env.mcp.secrets ($(grep -c '=' .env.mcp.secrets) values)"
